module.exports={
    PRODUCT_COLLECTION:process.env.PRODUCT_COLLECTION,
    USER_COLLECTION:process.env.USER_COLLECTION,
    ADMIN_COLLECTION:process.env.ADMIN_COLLECTION,
    CATEGORY_COLLECTION:process.env.CATEGORY_COLLECTION,
    CART_COLLECTION :process.env.CART_COLLECTION,
    ORDER_COLLECTION:process.env.ORDER_COLLECTION,
    CATEGORY_OFFERS: process.env.CATEGORY_OFFERS,
    PRODUCT_OFFERS: process.env.PRODUCT_OFFERS,
    BANNER_COLLECTION: process.env.BANNER_COLLECTION
}